# Generated by Django 3.0.4 on 2020-06-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200625_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificado',
            options={'ordering': ['created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
