# Generated by Django 3.0.4 on 2020-06-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200624_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'proyectoaaa', 'verbose_name_plural': 'proyectos'},
        ),
    ]
