# Generated by Django 3.0.4 on 2020-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200625_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'Clasificado', 'verbose_name_plural': 'Clasificados'},
        ),
        migrations.AddField(
            model_name='project',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Youtube'),
        ),
    ]
