# Generated by Django 3.0.4 on 2020-06-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200625_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created'], 'verbose_name': 'Clasificado', 'verbose_name_plural': 'Clasificados'},
        ),
    ]
